<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Securityzator.Application\Securityzator.Application.csproj" SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="..\Securityzator.Infrastructure\Securityzator.Infrastructure.csproj" SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>

  <Target Name="EnsureStaticWebAssetsIntermediatePath" BeforeTargets="DefineStaticWebAssets">
    <MakeDir Directories="$(IntermediateOutputPath)" />
  </Target>

</Project>
